> {% client.global.set("auth_token", "123"); %}

###
# Test your FastAPI endpoints

GET http://127.0.0.1:9999/
Accept: application/json

###
GET http://127.0.0.1:9999/items/
Accept: application/json

###
GET http://127.0.0.1:9999/hello/User
Accept: application/json

###

GET  http://127.0.0.1:9999/items/79
Accept: application/json
Authorization: Bearer 123456

###

POST http://127.0.0.1:9999/token
Content-Type: application/x-www-form-urlencoded

username=johndoe&password=secret

###
POST http://127.0.0.1:9999/token
Content-Type: application/x-www-form-urlencoded

username=johndoe999&password=secret

###
GET http://127.0.0.1:9999/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNjk3OTY3NDU2fQ.z4eKldnS37bTH79OEJgDvaP7DJKTAkZ03Lct6m1pJHo

###
GET http://127.0.0.1:9999/users/me

###
GET http://127.0.0.1:9999/users/me
Authorization: Bearer johndoe111

###
GET http://127.0.0.1:9999/hello_world

###
GET http://127.0.0.1:9999/users/

###
POST http://127.0.0.1:9999/users/
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###
POST http://127.0.0.1:9999/send-notification/123456.qq.com?q=iambigman
Content-Type: application/json

###
GET http://127.0.0.1:9999/query-checker/


###
GET http://127.0.0.1:9999/api/v1/app


###
GET http://127.0.0.1:9999/items/666

